services:
  scrapping_imm:
    build: .
    container_name: scrapping_imm
    env_file:
      - .env
    volumes:
      - ./annonces_vues.json:/app/annonces_vues.json
      - ./user_data:/app/user_data
    environment:
      - PYTHONUNBUFFERED=1 
      - HEADLESS=False 
    restart: unless-stopped